use std::{env, fs, io::ErrorKind, sync::Arc};

use async_trait::async_trait;
use autoagents::{
    core::agent::{
        memory::SlidingWindowMemory,
        prebuilt::executor::{ReActAgent, ReActAgentOutput},
        task::Task,
        AgentBuilder, AgentOutputT, DirectAgent,
    },
    core::error::Error,
    core::tool::{ToolCallError, ToolInputT, ToolRuntime},
    init_logging,
    llm::{backends::openai::OpenAI, builder::LLMBuilder},
};
use autoagents_derive::{agent, tool, AgentHooks, AgentOutput, ToolInput};
use clap::Parser;
use serde::{Deserialize, Serialize};
use serde_json::{json, Value};

#[derive(Parser, Debug)]
#[command(version, about = "SoutoAgent provisioning for PackageKit migration")]
struct Args {
    /// Task statement passed to SoutoAgent. Defaults to proxmod migration brief.
    #[arg(
        long,
        default_value = "Plan the proxmod-to-PackageKit migration package by package, focusing on dbus transactions"
    )]
    task: String,

    /// Path to pk-known.map.tsv generated by pk-known-start.sh
    #[arg(long, default_value = "/root/pk-known/pk-known.map.tsv")]
    pk_map: String,

    /// Path to pk-known.details.tsv generated by pk-known-start.sh
    #[arg(long, default_value = "/root/pk-known/pk-known.details.tsv")]
    pk_details: String,

    /// Optional override for the OpenAI model name.
    #[arg(long, default_value = "gpt-4o")]
    model: String,
}

#[tokio::main]
async fn main() -> Result<(), Error> {
    init_logging();
    let args = Args::parse();

    let api_key = env::var("OPENAI_API_KEY")
        .map_err(|_| Error::CustomError("OPENAI_API_KEY must be set for SoutoAgent".into()))?;

    env::set_var("PK_KNOWN_MAP", &args.pk_map);
    env::set_var("PK_KNOWN_DETAILS", &args.pk_details);

    let llm: Arc<OpenAI> = LLMBuilder::<OpenAI>::new()
        .api_key(api_key)
        .model(&args.model)
        .max_tokens(1024)
        .temperature(0.1)
        .build()
        .expect("Failed to configure LLM");

    let sliding_window_memory = Box::new(SlidingWindowMemory::new(20));

    let souto_agent = ReActAgent::new(SoutoAgent {});
    let agent_handle = AgentBuilder::<_, DirectAgent>::new(souto_agent)
        .llm(llm)
        .memory(sliding_window_memory)
        .build()
        .await?;

    let task_prompt = format!(
        """
Context: You are coordinating the proxmod-to-PackageKit migration.
Reference data comes from pk-known-start.sh outputs located at:
- map: {map}
- details: {details}

Task: {task}

Produce a batch-wise migration plan that:
1. Confirms whether each dpkg name is resolvable via PackageKit.
2. Notes the PackageKit package-id + summary when available.
3. Suggests next DBus transactions (Resolve, GetDetails, InstallPackages) required to move control from proxmod to PackageKit.
4. Calls the PackageKitKnowledgeBase tool whenever you need canonical IDs.
""",
        map = args.pk_map,
        details = args.pk_details,
        task = args.task
    );

    let result = agent_handle
        .agent
        .run(Task::new(task_prompt.trim()))
        .await?;

    println!("SoutoAgent result:\n{}", serde_json::to_string_pretty(&result.json_value())?);
    Ok(())
}

#[derive(Debug, Serialize, Deserialize, ToolInput)]
pub struct PackageLookupInput {
    #[input(description = "dpkg package name managed by proxmod")]
    package_name: String,
    #[input(description = "Optional override for the pk-known.map.tsv path")]
    map_path: Option<String>,
    #[input(description = "Optional override for the pk-known.details.tsv path")]
    details_path: Option<String>,
}

#[tool(
    name = "PackageKitKnowledgeBase",
    description = "Resolves dpkg names to PackageKit package-ids using pk-known-start.sh artifacts and surfaces summaries for migration planning.",
    input = PackageLookupInput,
)]
pub struct PackageKitKnowledgeBase;

#[async_trait]
impl ToolRuntime for PackageKitKnowledgeBase {
    async fn execute(&self, args: Value) -> Result<Value, ToolCallError> {
        let input: PackageLookupInput = serde_json::from_value(args)?;
        let map_path = input
            .map_path
            .or_else(|| env::var("PK_KNOWN_MAP").ok())
            .unwrap_or_else(|| "/root/pk-known/pk-known.map.tsv".into());
        let details_path = input
            .details_path
            .or_else(|| env::var("PK_KNOWN_DETAILS").ok())
            .unwrap_or_else(|| "/root/pk-known/pk-known.details.tsv".into());

        let (package_id, missing_artifacts) = lookup_package_id(&map_path, &input.package_name)?;
        let summary = if let Some(id) = &package_id {
            lookup_package_summary(&details_path, id)?
        } else {
            None
        };

        Ok(json!({
            "package_name": input.package_name,
            "package_id": package_id,
            "summary": summary,
            "map_path_used": map_path,
            "details_path_used": details_path,
            "missing_artifacts": missing_artifacts,
        }))
    }
}

fn lookup_package_id(map_path: &str, package: &str) -> Result<(Option<String>, Vec<String>), ToolCallError> {
    let mut missing = Vec::new();
    match fs::read_to_string(map_path) {
        Ok(content) => {
            for line in content.lines() {
                if line.trim().is_empty() {
                    continue;
                }
                let mut parts = line.split('\t');
                let name = parts.next().unwrap_or("").trim();
                let id = parts.next().unwrap_or("").trim();
                if name == package {
                    return Ok((Some(id.to_string()), missing));
                }
            }
            Ok((None, missing))
        }
        Err(err) => match err.kind() {
            ErrorKind::NotFound => {
                missing.push(format!("missing map file: {}", map_path));
                Ok((None, missing))
            }
            _ => Err(ToolCallError::RuntimeError(Box::new(err))),
        },
    }
}

fn lookup_package_summary(details_path: &str, package_id: &str) -> Result<Option<String>, ToolCallError> {
    match fs::read_to_string(details_path) {
        Ok(content) => {
            for line in content.lines() {
                if line.trim().is_empty() {
                    continue;
                }
                let mut parts = line.split('\t');
                let id = parts.next().unwrap_or("").trim();
                if id == package_id {
                    let summary = parts.collect::<Vec<_>>().join("\t").trim().to_string();
                    return Ok(Some(summary));
                }
            }
            Ok(None)
        }
        Err(err) => match err.kind() {
            ErrorKind::NotFound => Ok(None),
            _ => Err(ToolCallError::RuntimeError(Box::new(err))),
        },
    }
}

#[derive(Debug, Serialize, Deserialize, AgentOutput)]
pub struct SoutoAgentOutput {
    #[output(description = "Narrative response from the agent")] 
    response: String,
    #[output(description = "Optional structured action plan" )]
    action_plan: Option<Value>,
}

impl From<ReActAgentOutput> for SoutoAgentOutput {
    fn from(value: ReActAgentOutput) -> Self {
        if value.done {
            if let Ok(parsed) = serde_json::from_str::<SoutoAgentOutput>(&value.response) {
                return parsed;
            }
        }
        SoutoAgentOutput {
            response: value.response,
            action_plan: None,
        }
    }
}

#[agent(
    name = "souto_agent",
    description = "You are SoutoAgent, responsible for migrating proxmod-managed packages toward PackageKit DBus transactions. Generate deterministic playbooks that reference PackageKit package-ids, repository provenance, and the required pkcon transactions (resolve, get-details, install, remove). Explain how proxmod ownership is replaced by PackageKit per package, note blockers, and stage work in batches of <=25 packages.",
    tools = [PackageKitKnowledgeBase],
    output = SoutoAgentOutput,
)]
#[derive(Clone, AgentHooks)]
pub struct SoutoAgent;
