name: CI Checks

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - "**"

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install system dependencies
        run: sudo apt-get update && sudo apt-get install -y libssl-dev pkg-config
      # Install Rust toolchain
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          override: true
          components: llvm-tools-preview,rustfmt,clippy

      # Formatting check
      - name: Run fmt
        run: cargo fmt -- --check

      # Clippy lint
      - name: Run clippy
        run: cargo clippy --all-features --all-targets -- -D warnings

      # Run tests
      - name: Run tests
        run: cargo test --workspace --exclude autoagents-burn --exclude wasm_agent

      # Cargo check
      - name: Run cargo check
        run: cargo check --all-features --all-targets
